services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=xadmin'
      - 'POSTGRES_PASSWORD=xadmin'
      - 'POSTGRES_USER=xadmin'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
